# numpy 数学运算, 随机数, 线性代数   

对于一维的 array, 只要是 Python 列表支持的下标相关的方法, array也都支持，所以在此没有特别列出。


## 1. 基础数学运算

既然叫numerical python，基础数学运算也是强大的.   


np.abs()   绝对值   
np.sin()  
np.pi  
np.cos()  
np.arctanh()  反正切   
np.exp()  
np.power()  
np.dot()  
np.sqrt()  
np.sum()  
np.size()     返回数组中所有元素的个数   
np.shape()    返回数组的维度信息   
np.max()    
np.min()    
np.argmax()      返回数组中元素的最大值的索引   
np.reval()    
np.mean()      返回数组的均值   
np.std()  
np.flatten()   展开数组   
np.ravel('C')  展开数组, 'C' 是按行展开; 'F' 是按列展开   

`+`   
`-`   
`*`    
`/`   
`**`    幂次   



In [47]:
import numpy as np

a = np.sin(np.pi/2)
b = np.exp(1)
c = np.dot([1,2,3], [1, 2, 3])

a = np.array([[1,2,3], [4, 5, 6]])
b = np.array([[1,2,3], [1, 2, 3]])
a**b 


1

## 2. 矩阵运算的广播机制   

对于 array，默认执行`对位运算`。   

涉及到多个 array 的对位运算需要 array 的维度一致，如果一个 array 的维度和另一个 array 的子维度一致，则在没有对齐的维度上分别执行对位运算，这种机制叫做 `广播（broadcasting）`.    

广播机制让计算的表达式保持简洁.    

In [9]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
d = np.array([2, 2, 2])
c-1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## 3. 线性代数模块（linalg）

在深度学习相关的数据处理和运算中，线性代数模块（linalg）是最常用的之一。    

结合numpy提供的基本函数，可以对向量，矩阵，或是说多维张量进行一些基本的运算.   

np.linalg.norm(a)  向量的模     
np.linalg.det(b)   矩阵的行列式
np.linalg.matrix_rank(b)  求矩阵的秩
np.dot(b, c)       矩阵和向量的乘法   
np.trace(b)        矩阵的迹   
u, v = np.linalg.eig(d)  求矩阵的特征值和特征向量.   
l = np.linalg.cholesky(d)  Cholesky 分解并重建, np.dot(l, l.T) == d
U, s, V = np.linalg.svd(e) 对不镇定矩阵，进行 SVD 分解并重建

**Note**    

np.linalg.eig()是一般情况的本征值分解，对于更常见的对称实数矩阵.    

np.linalg.eigh()更快且更稳定，不过输出的值的顺序和eig()是相反的.    


In [20]:
a = np.array([3, 4])
np.linalg.norm(a)

b = np.array([
    [1, 2, 3],
    [4, 8, 6],
    [7, 8, 9]
])
d = np.array([
    [1, 0, 0],
    [0, 8, 0],
    [0, 0, 9]
])
c = np.array([1, 0, 1])
np.trace(b)
np.linalg.det(d)

# Cholesky 还原
l = np.linalg.cholesky(d)
np.dot(l, l.T)


# svd 还原
U, s, V = np.linalg.svd(b)
S = np.array([
    [s[0], 0, 0],
    [0, s[1], 0],
    [0, 0, s[2]]
])
np.dot(U, np.dot(S, V))

array([[1., 2., 3.],
       [4., 8., 6.],
       [7., 8., 9.]])

## 4. 随机模块（random）

随机模块包含了随机数产生和统计分布相关的基本函数，Python 本身也有随机模块 random，不过 numpy 的随机模块功能更丰富.   


random.rand(1, 3)   产生一个1x3，`[0,1)`之间的浮点型随机数   
random.random(n)     产生 n 个`[0,1)`之间的浮点型随机数    random.uniform(low, high, size)   产生 size 个`[low, high)`之间的浮点型随机数    
random.randint(1, 6, 10)  产生10个`[1,6)`之间的整型随机数  
random.normal(size=(5, 2))  产生 2x5 的标准正态分布样本  
random.binomial(n=5, p=0.5, size=5) 产生5个，n=5，p=0.5的二项分布样本   
random.choice(a, 7)   从 a 中有回放的随机采样7个   
random.choice(a, 7, replace=False)   从a中无回放的随机采样7个   
b = random.permutation(a)  a 进行乱序并返回一个新的array   
random.shuffle(a)   对a进行in-place乱序    
random.bytes(9)   生成一个长度为9的随机bytes序列并作为str返回   


In [44]:
import numpy.random as random
random.seed(42)

random.rand(1, 2)
random.random()

# 下边4个没有区别，都是按照指定大小产生[0,1)之间的浮点型随机数array，不Pythonic…
random.random((3, 3))
random.sample((3, 3))
random.random_sample((3, 3))
random.ranf((3, 3))

random.random(10)
random.uniform(1, 6, 3)
random.normal(size = (5, 2))
a = np.arange(10)
random.choice(a, 7)
random.choice(a, 7, replace=False)
random.permutation(a)
random.shuffle(a)
random.bytes(9)


b'"\xa6\xad\x8f\xc0\x13\xe3x\xe2'

随机模块可以很方便地让我们做一些快速模拟去验证一些结论。   

比如来考虑一个非常违反直觉的概率题例子：一个选手去参加一个TV秀，有三扇门，其中一扇门后有奖品，这扇门只有主持人知道。选手先随机选一扇门，但并不打开，主持人看到后，会打开其余两扇门中没有奖品的一扇门。然后，主持人问选手，是否要改变一开始的选择？    

这个问题的答案是应该改变一开始的选择。在第一次选择的时候，选错的概率是2/3，选对的概率是1/3。第一次选择之后，主持人相当于帮忙剔除了一个错误答案，所以如果一开始选的是错的，这时候换掉就选对了；而如果一开始就选对，则这时候换掉就错了。根据以上，一开始选错的概率就是换掉之后选对的概率（2/3），这个概率大于一开始就选对的概率（1/3），所以应该换。虽然道理上是这样，但是还是有些绕，要是通过推理就是搞不明白怎么办，没关系，用随机模拟就可以轻松得到答案.
  

In [ ]:
import numpy.random as random

random.seed(42)

# 做10000次实验
n_tests = 10000

# 生成每次实验的奖品所在的门的编号
# 0表示第一扇门，1表示第二扇门，2表示第三扇门
winning_doors = random.randint(0, 3, n_tests)

# 记录如果换门的中奖次数
change_mind_wins = 0

# 记录如果坚持的中奖次数
insist_wins = 0

# winning_door就是获胜门的编号
for winning_door in winning_doors:

    # 随机挑了一扇门
    first_try = random.randint(0, 3)
    
    # 其他门的编号
    remaining_choices = [i for i in range(3) if i != first_try]
  
    # 没有奖品的门的编号，这个信息只有主持人知道
    wrong_choices = [i for i in range(3) if i != winning_door]

    # 一开始选择的门主持人没法打开，所以从主持人可以打开的门中剔除
    if first_try in wrong_choices:
        wrong_choices.remove(first_try)
    
    # 这时wrong_choices变量就是主持人可以打开的门的编号
    # 注意此时如果一开始选择正确，则可以打开的门是两扇，主持人随便开一扇门
    # 如果一开始选到了空门，则主持人只能打开剩下一扇空门
    screened_out = random.choice(wrong_choices)
    remaining_choices.remove(screened_out)
    
    # 所以虽然代码写了好些行，如果策略固定的话，
    # 改变主意的获胜概率就是一开始选错的概率，是2/3
    # 而坚持选择的获胜概率就是一开始就选对的概率，是1/3
    
    # 现在除了一开始选择的编号，和主持人帮助剔除的错误编号，只剩下一扇门
    # 如果要改变注意则这扇门就是最终的选择
    changed_mind_try = remaining_choices[0]

    # 结果揭晓，记录下来
    change_mind_wins += 1 if changed_mind_try == winning_door else 0
    insist_wins += 1 if first_try == winning_door else 0

# 输出10000次测试的最终结果，和推导的结果差不多：
# You win 6616 out of 10000 tests if you changed your mind
# You win 3384 out of 10000 tests if you insist on the initial choice
print(
    'You win {1} out of {0} tests if you changed your mind\n'
    'You win {2} out of {0} tests if you insist on the initial choice'.format(
        n_tests, change_mind_wins, insist_wins
        )
)


## 5. 最大最小化   

- np.maximum(a,b,c,…..) 返回每个索引位置上的最大值，np.minimum(…….) 相反   


(5, 5)
(4, 5)
[[ 7 15 11  8  7]
 [19 11 11  4  8]
 [ 3  2 12  6  2]
 [ 1 12 12 17 10]
 [16 15 15 19 12]]
I= [[ 7 15 11  8  7]
 [ 3  2 12  6  2]
 [16 15 15 19 12]]


[0, 1, 2, 3, 4]